"""Added account table

Revision ID: 730f90ab9b56
Revises: 
Create Date: 2022-12-23 03:38:33.018679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '730f90ab9b56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('order_form_number', sa.VARCHAR(length=255), nullable=False, comment='Номер бланка заказа'),
    sa.Column('order_form_date', sa.Date(), nullable=True, comment='Дата бланка заказа'),
    sa.Column('contract_number', sa.VARCHAR(length=255), nullable=False, comment='Номер договора'),
    sa.Column('contract_date', sa.Date(), nullable=True, comment='Дата заключения договора'),
    sa.Column('service', sa.VARCHAR(length=255), nullable=False, comment='Услуга'),
    sa.Column('type_order_prod', sa.BOOLEAN(), nullable=False),
    sa.Column('authorized_persons_of_the_contractor', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Уполномоченные лица исполнителя'),
    sa.Column('authorized_persons_of_the_customer', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Уполномоченные лица заказчика'),
    sa.Column('technical_parameters_of_the_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Технические параметры услуг'),
    sa.Column('tariffs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Тарифы БЗ'),
    sa.Column('date_of_technological_readiness_of_services', sa.Date(), nullable=True, comment='Дата технологической готовности оказания услуги'),
    sa.Column('service_billing_start_date', sa.Date(), nullable=True),
    sa.Column('service_billing_stop_date', sa.Date(), nullable=True),
    sa.Column('initial_term_of_service_provision', sa.INTEGER(), nullable=False),
    sa.Column('service_source', sa.VARCHAR(length=255), nullable=False, comment='Где описана услуга'),
    sa.Column('special_pricing_conditions_for_services', sa.Text(), nullable=True),
    sa.Column('signatories', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Подписанты'),
    sa.Column('consumer_organization', sa.VARCHAR(length=255), nullable=False, comment='Организация заказчика'),
    sa.Column('template_form', sa.VARCHAR(length=255), nullable=False),
    sa.Column('template_blank', sa.VARCHAR(length=255), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('previous_order_for', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('next_order_form', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_tariffs',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tariff_concat_code', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_tariffs')
    op.drop_table('order')
    # ### end Alembic commands ###
