"""Added delete cascade

Revision ID: 4757d09fceda
Revises: 72c0cc73859c
Create Date: 2023-01-03 01:08:41.807959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4757d09fceda'
down_revision = '72c0cc73859c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'message_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('comments', 'author_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('comments_message_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_author_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('connected_chat_rooms', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('connected_chat_rooms', 'chat_room_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('connected_chat_rooms_user_id_fkey', 'connected_chat_rooms', type_='foreignkey')
    op.drop_constraint('connected_chat_rooms_chat_room_id_fkey', 'connected_chat_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'connected_chat_rooms', 'chat_rooms', ['chat_room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connected_chat_rooms', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'chat_room_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('messages', 'author_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('messages_chat_room_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_author_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'chat_rooms', ['chat_room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_author_id_fkey', 'messages', 'users', ['author_id'], ['id'])
    op.create_foreign_key('messages_chat_room_id_fkey', 'messages', 'chat_rooms', ['chat_room_id'], ['id'])
    op.alter_column('messages', 'author_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('messages', 'chat_room_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint(None, 'connected_chat_rooms', type_='foreignkey')
    op.drop_constraint(None, 'connected_chat_rooms', type_='foreignkey')
    op.create_foreign_key('connected_chat_rooms_chat_room_id_fkey', 'connected_chat_rooms', 'chat_rooms', ['chat_room_id'], ['id'])
    op.create_foreign_key('connected_chat_rooms_user_id_fkey', 'connected_chat_rooms', 'users', ['user_id'], ['id'])
    op.alter_column('connected_chat_rooms', 'chat_room_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('connected_chat_rooms', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_author_id_fkey', 'comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key('comments_message_id_fkey', 'comments', 'messages', ['message_id'], ['id'])
    op.alter_column('comments', 'author_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('comments', 'message_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
